INSERT INTO processes (id, name) VALUES (1000, 'Some Process');
INSERT INTO processes (id, name) VALUES (1001, 'Process#0');
INSERT INTO processes (id, name) VALUES (1002, 'Process#1');
INSERT INTO processes (id, name) VALUES (1003, 'Process#2');
INSERT INTO processes (id, name) VALUES (1004, 'Process#3');
INSERT INTO processes (id, name) VALUES (1005, 'Process#4');
INSERT INTO processes (id, name) VALUES (1006, 'Process#5');
INSERT INTO processes (id, name) VALUES (1007, 'Process#6');
INSERT INTO processes (id, name) VALUES (1008, 'Process#7');
INSERT INTO processes (id, name) VALUES (1009, 'Process#8');
INSERT INTO processes (id, name) VALUES (1010, 'Process#9');
